workspace:
  base: /go
  path: src/github.com/kowala-tech/kUSD

pipeline:

  test:
    image: kowalatech/go:1.0.1
    commands:
      - make test
    when:
      event: [push]
      branch: [feature/*, hotfix/*]

  build:
    image: golang
    commands:
      - make
    when:
      event: [push, tag]
      branch: [master, develop, refs/tags/*]

  github_release:
    image: plugins/github-release
    secrets: [ github_release_api_key ] 
    files:
      - build/bin/kusd
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
    when:
      event: tag

  docker_kusd:
    image: plugins/docker
    repo: kowala-tech/kusd
    secrets: [ docker_username, docker_password ]
    tags: latest
    dockerfile: kusd.Dockerfile
    when:
      branch: [master, develop]

  docker_bootnode:
    image: plugins/docker
    repo: kowala-tech/bootnode
    secrets: [ docker_username, docker_password ]
    tags: latest
    dockerfile: bootnode.Dockerfile
    when:
      branch: [master, develop]
